Added new options to HomingMissileSpell
TheComputerGeek2/MagicSpells pull request #792
Opened 2023-10-27 00:04 UTC by HyperDir

Added:
projectile-horiz-offset
projectile-vert-offset
projectile-horiz-spread
projectile-vert-spread

2023-10-27 17:59 UTC, Chronoken requested changes
Please adjust those before its merged, other than that looks good to me.

2023-10-27 17:59 UTC, Chronoken commented on core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
> +		Random rand = ThreadLocalRandom.current();
`Spell` class has a `random` variable, use that instead of declaring a new thread local random.

2023-10-27 17:59 UTC, Chronoken commented on core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
> +				float rx = -1 + rand.nextFloat() * 2;
Switch to `random` from `Spell` class.

2023-10-27 17:59 UTC, Chronoken commented on core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
> +				float ry = -1 + rand.nextFloat() * 2;
Switch to `random` from `Spell` class.

2023-10-27 17:59 UTC, Chronoken commented on core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
> +				float rz = -1 + rand.nextFloat() * 2;
Switch to `random` from `Spell` class.

2023-10-27 17:59 UTC, Chronoken commented on core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
> +}
New line at the end please.

2023-10-27 22:18 UTC, HyperDir commented
All done. Thanks for the review.

2023-10-28 09:02 UTC, Chronoken approved these changes

2023-10-28 09:02 UTC, merged