Fix MessageListener
TheComputerGeek2/MagicSpells pull request #958
Opened 2024-12-01 17:09 UTC by JasperLorelai

2024-12-09 00:45 UTC, JasperLorelai commented
aa8336e requires comment changes due to merging of https://github.com/PaperMC/Paper/pull/11715/

2024-12-16 20:21 UTC, JasperLorelai commented
Removed removal suppressions on aa8336e.

2024-12-18 19:19 UTC, TonytheMacaroni requested changes
Some small nitpicks.

2024-12-18 19:19 UTC, TonytheMacaroni commented on core/src/main/java/com/nisovin/magicspells/Spell.java
> +	 * @param key Path for the String or Config SpellFilter to be read from.
Capitalizing string and config here is a bit odd. Also, aren't they referred to as "section-based" spell filters? All spell filters are in configs, so calling them config spell filters is a bit weird.

2024-12-18 19:19 UTC, TonytheMacaroni commented on core/src/main/java/com/nisovin/magicspells/spells/buff/ext/DisguiseSpell.java
> +		if (!isConfigSection("disguise")) return;
Missing a newline here.

2024-12-18 19:19 UTC, TonytheMacaroni commented on core/src/main/java/com/nisovin/magicspells/spells/targeted/SlimeSizeSpell.java
> +		if (!SLIME.isValidTarget(data.target())) return noTarget(data);
Is this change necessary? The instanceof seems more clear.

2024-12-18 19:21 UTC, TonytheMacaroni commented on core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/UsingCondition.java
> +		return true;
This should be `itemData != null || var.isEmpty()`. An invalid magic item should cause an error.

2024-12-18 19:35 UTC, TonytheMacaroni commented on core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/UsingCondition.java
> +		return true;
Actually, probably should do:
```java
if (var.isEmpty()) return true;
itemData = MagicItems.getMagicItemDataFromString(var);
return itemData != null;
```

2024-12-22 02:40 UTC, merged